import type { JournalEntry, UserProfile } from './types';

export const initialUsers: UserProfile[] = [
  {
    id: 'maya',
    name: 'Maya Chen',
    city: 'Lisbon, PT',
    country: 'Portugal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    languages: ['Portuguese', 'English', 'French'],
    interests: ['postcards', 'street art', 'cafe hopping', 'history'],
    bio: 'A sketchbook-carrying storyteller chasing coastline cafes and sunset postcards.',
    matchingNotes: 'Loves illustrated journals and urban discovery walks.',
    favoriteStamp: 'Azulejo tile',
    responseTime: '2 days',
  },
  {
    id: 'nina',
    name: 'Nina Patel',
    city: 'Mumbai, IN',
    country: 'India',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=256&q=80',
    languages: ['English', 'Hindi', 'Spanish'],
    interests: ['heritage food', 'markets', 'museum sketches', 'street music'],
    bio: 'I write letters from hidden bazaars, spice markets, and sleepy train platforms.',
    matchingNotes: 'Perfect travel penpal for cultural swaps and recipe notes.',
    favoriteStamp: 'Monsoon train',
    responseTime: '4 days',
  },
  {
    id: 'lucas',
    name: 'Lucas Rivera',
    city: 'San Juan, PR',
    country: 'Puerto Rico',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    languages: ['Spanish', 'English'],
    interests: ['coastal drives', 'postcards', 'nature trails', 'archival maps'],
    bio: 'A penpal for slow mornings, sunrise poems, and island road-trip snapshots.',
    matchingNotes: 'Great match for anyone who loves ocean colors and travel journals.',
    favoriteStamp: 'Harbor lighthouse',
    responseTime: '1 day',
  },
  {
    id: 'aya',
    name: 'Aya Kim',
    city: 'Kyoto, JP',
    country: 'Japan',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
    languages: ['Japanese', 'English', 'Korean'],
    interests: ['temple walks', 'calligraphy', 'tea gardens', 'museum sketches'],
    bio: 'Sharing quiet travel letters full of paper tickets and seasonal rituals.',
    matchingNotes: 'Ideal if you enjoy artistic travel stories and soft adventure.',
    favoriteStamp: 'Ink crane',
    responseTime: '3 days',
  },
  {
    id: 'elias',
    name: 'Elias Morgan',
    city: 'Reykjavik, IS',
    country: 'Iceland',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    languages: ['Icelandic', 'English', 'Danish'],
    interests: ['nature trails', 'film photography', 'hot springs', 'archival maps'],
    bio: 'I send northern-light postcards, weather notes, and tiny sketches of mossy lava fields.',
    matchingNotes: 'A calm match for hikers, photographers, and map collectors.',
    favoriteStamp: 'Aurora compass',
    responseTime: '5 days',
  },
  {
    id: 'sofia',
    name: 'Sofia Marino',
    city: 'Naples, IT',
    country: 'Italy',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=256&q=80',
    languages: ['Italian', 'English', 'Spanish'],
    interests: ['cafe hopping', 'heritage food', 'postcards', 'street art'],
    bio: 'Writing from sun-faded balconies, ferry decks, and bakeries that smell like old family stories.',
    matchingNotes: 'Brilliant for food memories, coastal letters, and city wanderers.',
    favoriteStamp: 'Lemon ferry',
    responseTime: '2 days',
  },
];

export const initialJournalEntries: JournalEntry[] = [
  {
    id: 'entry-1',
    photo: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80',
    location: 'Lisbon, Portugal',
    date: '2026-03-21',
    mood: 'Inspired',
    story: 'A sunrise walk through mosaic alleys, a cup of coffee at a hidden tile shop, and a long letter drafted on a seaside breeze.',
    coordinates: { lat: 38.7223, lng: -9.1393 },
  },
  {
    id: 'entry-2',
    photo: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    location: 'Kyoto, Japan',
    date: '2026-04-12',
    mood: 'Relaxed',
    story: 'Cherry blossoms and paper lanterns created a soft journal entry night. I traced old ink strokes while listening to temple bells.',
    coordinates: { lat: 35.0116, lng: 135.7681 },
  },
  {
    id: 'entry-3',
    photo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    location: 'San Juan, Puerto Rico',
    date: '2026-05-05',
    mood: 'Adventurous',
    story: 'Salt on my sleeves, pastel streets under my shoes, and a postcard mailed before the afternoon storm rolled across the bay.',
    coordinates: { lat: 18.4655, lng: -66.1057 },
  },
];
