import type { JournalEntry, UserProfile } from './types';

export const initialUsers: UserProfile[] = [
  {
    id: 'maya',
    name: 'Maya Chen',
    city: 'Lisbon, PT',
    country: 'Portugal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    languages: ['Portuguese', 'English', 'French'],
    interests: ['postcards', 'street art', 'cafe hopping', 'history'],
    bio: 'A sketchbook-carrying storyteller chasing coastline cafes and sunset postcards.',
    matchingNotes: 'Loves illustrated journals and urban discovery walks.',
    favoriteStamp: 'Azulejo tile',
    responseTime: '2 days',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Slow wandering',
      letterStyle: 'Long reflective letters',
      socialEnergy: 'Quiet corners',
      planningStyle: 'Loose outline',
      exchangeStyle: 'Creative prompts',
    },
  },
  {
    id: 'nina',
    name: 'Nina Patel',
    city: 'Mumbai, IN',
    country: 'India',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=256&q=80',
    languages: ['English', 'Hindi', 'Spanish'],
    interests: ['heritage food', 'markets', 'museum sketches', 'street music'],
    bio: 'I write letters from hidden bazaars, spice markets, and sleepy train platforms.',
    matchingNotes: 'Perfect travel penpal for cultural swaps and recipe notes.',
    favoriteStamp: 'Monsoon train',
    responseTime: '4 days',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Local rhythm',
      letterStyle: 'Photo-heavy updates',
      socialEnergy: 'Big city buzz',
      planningStyle: 'Follow the moment',
      exchangeStyle: 'Practical tips',
    },
  },
  {
    id: 'lucas',
    name: 'Lucas Rivera',
    city: 'San Juan, PR',
    country: 'Puerto Rico',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
    languages: ['Spanish', 'English'],
    interests: ['coastal drives', 'postcards', 'nature trails', 'archival maps'],
    bio: 'A penpal for slow mornings, sunrise poems, and island road-trip snapshots.',
    matchingNotes: 'Great match for anyone who loves ocean colors and travel journals.',
    favoriteStamp: 'Harbor lighthouse',
    responseTime: '1 day',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Local rhythm',
      letterStyle: 'Short postcards',
      socialEnergy: 'Flexible energy',
      planningStyle: 'Follow the moment',
      exchangeStyle: 'Deep stories',
    },
  },
  {
    id: 'aya',
    name: 'Aya Kim',
    city: 'Kyoto, JP',
    country: 'Japan',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
    languages: ['Japanese', 'English', 'Korean'],
    interests: ['temple walks', 'calligraphy', 'tea gardens', 'museum sketches'],
    bio: 'Sharing quiet travel letters full of paper tickets and seasonal rituals.',
    matchingNotes: 'Ideal if you enjoy artistic travel stories and soft adventure.',
    favoriteStamp: 'Ink crane',
    responseTime: '3 days',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Slow wandering',
      letterStyle: 'Long reflective letters',
      socialEnergy: 'Quiet corners',
      planningStyle: 'Plan ahead',
      exchangeStyle: 'Creative prompts',
    },
  },
  {
    id: 'elias',
    name: 'Elias Morgan',
    city: 'Reykjavik, IS',
    country: 'Iceland',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    languages: ['Icelandic', 'English', 'Danish'],
    interests: ['nature trails', 'film photography', 'hot springs', 'archival maps'],
    bio: 'I send northern-light postcards, weather notes, and tiny sketches of mossy lava fields.',
    matchingNotes: 'A calm match for hikers, photographers, and map collectors.',
    favoriteStamp: 'Aurora compass',
    responseTime: '5 days',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Slow wandering',
      letterStyle: 'Photo-heavy updates',
      socialEnergy: 'Quiet corners',
      planningStyle: 'Loose outline',
      exchangeStyle: 'Deep stories',
    },
  },
  {
    id: 'sofia',
    name: 'Sofia Marino',
    city: 'Naples, IT',
    country: 'Italy',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=256&q=80',
    languages: ['Italian', 'English', 'Spanish'],
    interests: ['cafe hopping', 'heritage food', 'postcards', 'street art'],
    bio: 'Writing from sun-faded balconies, ferry decks, and bakeries that smell like old family stories.',
    matchingNotes: 'Brilliant for food memories, coastal letters, and city wanderers.',
    favoriteStamp: 'Lemon ferry',
    responseTime: '2 days',
    isSample: true,
    vibeProfile: {
      travelTempo: 'Local rhythm',
      letterStyle: 'Short postcards',
      socialEnergy: 'Big city buzz',
      planningStyle: 'Follow the moment',
      exchangeStyle: 'Practical tips',
    },
  },
];

export const initialJournalEntries: JournalEntry[] = [
  {
    id: 'entry-1',
    photo: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80',
    galleryPhotos: [
      'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513735492246-483525079686?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?auto=format&fit=crop&w=800&q=80',
    ],
    location: 'Lisbon, Portugal',
    date: '2026-03-21',
    mood: 'Inspired',
    story: 'A sunrise walk through mosaic alleys, a cup of coffee at a hidden tile shop, and a long letter drafted on a seaside breeze.',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    reviews: [
      {
        id: 'review-lisbon-maya',
        authorName: 'Maya Chen',
        authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
        rating: 5,
        text: 'The tile shop note is perfect. I would add a tram ride to this route before sunset.',
        createdAt: '2026-03-23T11:00:00.000Z',
      },
      {
        id: 'review-lisbon-sofia',
        authorName: 'Sofia Marino',
        authorAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=256&q=80',
        rating: 4,
        text: 'Saved this for my next Portugal letter swap. The morning cafe detail feels so warm.',
        createdAt: '2026-03-25T16:30:00.000Z',
      },
    ],
    landmarks: [
      {
        id: 'landmark-belem',
        name: 'Belem Tower',
        type: 'Landmark',
        distance: '6.5 km',
        photo: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?auto=format&fit=crop&w=800&q=80',
        note: 'Best for late afternoon postcards and river photos.',
        rating: 4.8,
      },
      {
        id: 'landmark-alfama',
        name: 'Alfama Viewpoints',
        type: 'Viewpoint',
        distance: '1.2 km',
        photo: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=80',
        note: 'Climb early before the alleys fill with tour groups.',
        rating: 4.9,
      },
    ],
    restaurants: [
      {
        id: 'restaurant-taberna',
        name: 'Taberna da Rua',
        type: 'Portuguese plates',
        distance: '0.8 km',
        photo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        note: 'Small shared plates, hand-written menus, and a good solo counter.',
        rating: 4.6,
      },
      {
        id: 'restaurant-cafe',
        name: 'Cafe do Correio',
        type: 'Cafe',
        distance: '0.4 km',
        photo: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
        note: 'Quiet tables for journaling and mailing postcards.',
        rating: 4.7,
      },
    ],
  },
  {
    id: 'entry-2',
    photo: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    galleryPhotos: [
      'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80',
    ],
    location: 'Kyoto, Japan',
    date: '2026-04-12',
    mood: 'Relaxed',
    story: 'Cherry blossoms and paper lanterns created a soft journal entry night. I traced old ink strokes while listening to temple bells.',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    reviews: [
      {
        id: 'review-kyoto-aya',
        authorName: 'Aya Kim',
        authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
        rating: 5,
        text: 'This captures spring evenings beautifully. Try adding a temple stamp from a goshuin desk.',
        createdAt: '2026-04-14T09:15:00.000Z',
      },
    ],
    landmarks: [
      {
        id: 'landmark-fushimi',
        name: 'Fushimi Inari Taisha',
        type: 'Shrine',
        distance: '4.1 km',
        photo: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80',
        note: 'Go at sunrise for quiet paths through the gates.',
        rating: 4.9,
      },
      {
        id: 'landmark-gion',
        name: 'Gion Lanes',
        type: 'Historic district',
        distance: '1.8 km',
        photo: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80',
        note: 'Soft lantern light and narrow streets made for slow walking.',
        rating: 4.7,
      },
    ],
    restaurants: [
      {
        id: 'restaurant-soba',
        name: 'Soba Mado',
        type: 'Noodles',
        distance: '0.9 km',
        photo: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?auto=format&fit=crop&w=800&q=80',
        note: 'A quiet lunch stop with window seats and green tea.',
        rating: 4.5,
      },
      {
        id: 'restaurant-kissaten',
        name: 'Kissa Lantern',
        type: 'Kissaten',
        distance: '0.6 km',
        photo: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
        note: 'Retro coffee, thick toast, and calm letter-writing energy.',
        rating: 4.6,
      },
    ],
  },
  {
    id: 'entry-3',
    photo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    galleryPhotos: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596392301391-adee7f8b6a74?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=800&q=80',
    ],
    location: 'San Juan, Puerto Rico',
    date: '2026-05-05',
    mood: 'Adventurous',
    story: 'Salt on my sleeves, pastel streets under my shoes, and a postcard mailed before the afternoon storm rolled across the bay.',
    coordinates: { lat: 18.4655, lng: -66.1057 },
    reviews: [
      {
        id: 'review-sanjuan-lucas',
        authorName: 'Lucas Rivera',
        authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
        rating: 5,
        text: 'That storm timing is classic San Juan. Add El Morro to the walk if you can.',
        createdAt: '2026-05-06T13:45:00.000Z',
      },
    ],
    landmarks: [
      {
        id: 'landmark-morro',
        name: 'Castillo San Felipe del Morro',
        type: 'Fortress',
        distance: '1.6 km',
        photo: 'https://images.unsplash.com/photo-1596392301391-adee7f8b6a74?auto=format&fit=crop&w=800&q=80',
        note: 'Wide lawns, ocean wind, and dramatic old walls.',
        rating: 4.8,
      },
      {
        id: 'landmark-viejo',
        name: 'Old San Juan Streets',
        type: 'Historic walk',
        distance: '0.3 km',
        photo: 'https://images.unsplash.com/photo-1579689189009-874f5cac2db5?auto=format&fit=crop&w=800&q=80',
        note: 'Pastel homes, blue cobblestones, and easy photo corners.',
        rating: 4.9,
      },
    ],
    restaurants: [
      {
        id: 'restaurant-mofongo',
        name: 'Casa Mofongo',
        type: 'Puerto Rican kitchen',
        distance: '0.7 km',
        photo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
        note: 'Comforting plates after a windy fortress walk.',
        rating: 4.5,
      },
      {
        id: 'restaurant-paleta',
        name: 'Paleta Postal',
        type: 'Dessert stop',
        distance: '0.5 km',
        photo: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80',
        note: 'Bright frozen treats and sidewalk people-watching.',
        rating: 4.4,
      },
    ],
  },
];
